
USE GEFOR;

CREATE OR REPLACE TABLE USER (
    ID INT NOT NULL AUTO_INCREMENT , 
    EMAIL VARCHAR (255) NOT NULL,
    PSW VARCHAR (255) NOT NULL,
    -- 2 methods for primary key
    -- CONSTRAINT pk_user PRIMARY KEY (ID)
    PRIMARY KEY (ID)
);

INSERT INTO USER VALUES (null, 'test', 'testpsw');
INSERT INTO USER (EMAIL, PSW) VALUES ('test2', 'testpsw');