use todo_dev2;

DELIMITER //

CREATE OR REPLACE PROCEDURE insertTodos (
    IN p_texte VARCHAR(255)
) NOT DETERMINISTIC CONTAINS SQL
BEGIN
    INSERT INTO todo (texte) VALUES (p_texte);
END //

CREATE OR REPLACE PROCEDURE selectAllTodos () 
NOT DETERMINISTIC CONTAINS SQL
BEGIN
    SELECT id, texte FROM todo;
END //

CREATE OR REPLACE PROCEDURE deleteAllTodos ()
NOT DETERMINISTIC CONTAINS SQL
BEGIN
    DELETE FROM todo;
END //

CREATE OR REPLACE PROCEDURE selectTodoById (
    IN p_id INT
) 
NOT DETERMINISTIC CONTAINS SQL
BEGIN
    SELECT id, texte FROM todo WHERE id = p_id;
END //

CREATE OR REPLACE PROCEDURE deleteTodoById (
    IN p_id INT
) 
NOT DETERMINISTIC CONTAINS SQL
BEGIN
    DELETE FROM todo WHERE id = p_id;
END //

CREATE OR REPLACE PROCEDURE updateTodoById (
    IN p_id INT,
    IN p_texte VARCHAR(255)
) 
NOT DETERMINISTIC CONTAINS SQL
BEGIN
    UPDATE todo SET texte=p_texte WHERE id = p_id;
END //